export const PLANS_DATA = [
  {
    tier: "free",
    limits: {
      pdfs_per_month: 3,
      research_per_month: 5,
      chat_messages: 10,
      ppt: false,
      rag: false,
      academic_mode: false,
      history_days: 7,
      presentation_mode: false,
      share_links: false,
      comparison: false,
      priority_ai: false,
    },
    name: "Free",
    price: 0,
    billing: "monthly",
    currency: "USD",
    features: [
      "3 PDFs per month",
      "5 research topics per month",
      "10 chat messages per month",
      "In-app workspace viewer",
      "7-day history",
    ],
    highlight: false,
    tagline: "Try it tonight",
  },
  {
    tier: "student",
    limits: {
      pdfs_per_month: 20,
      research_per_month: 30,
      chat_messages: 50,
      ppt: true,
      rag: false,
      academic_mode: false,
      history_days: 180,
      presentation_mode: true,
      share_links: true,
      comparison: false,
      priority_ai: false,
    },
    name: "Student",
    price: 9,
    billing: "monthly",
    currency: "USD",
    features: [
      "20 PDFs per month",
      "30 research topics per month",
      "50 chat messages per month",
      "PPT export — 15-slide & 5-slide decks",
      "In-browser presentation mode",
      "Share workspace links",
      "180-day history",
    ],
    highlight: true,
    tagline: "For students who take presentations seriously",
  },
  {
    tier: "pro",
    limits: {
      pdfs_per_month: 60,
      research_per_month: 100,
      chat_messages: -1,
      ppt: true,
      rag: false,
      academic_mode: false,
      history_days: -1,
      presentation_mode: true,
      share_links: true,
      comparison: true,
      priority_ai: true,
    },
    name: "Pro",
    price: 19,
    billing: "monthly",
    currency: "USD",
    features: [
      "60 PDFs per month",
      "100 research topics per month",
      "Unlimited chat messages",
      "PPT export — 15-slide & 5-slide decks",
      "In-browser presentation mode",
      "Share workspace links",
      "Paper comparison mode",
      "GPT-4o — full model",
      "Forever history",
    ],
    highlight: false,
    tagline: "For researchers who need more, faster",
  },
  {
    tier: "scholar",
    limits: {
      pdfs_per_month: -1,
      research_per_month: -1,
      chat_messages: -1,
      ppt: true,
      rag: true,
      academic_mode: true,
      history_days: -1,
      presentation_mode: true,
      share_links: true,
      comparison: true,
      priority_ai: true,
    },
    name: "Scholar",
    price: 39,
    billing: "monthly",
    currency: "USD",
    features: [
      "Unlimited PDFs",
      "Unlimited research topics",
      "Unlimited chat messages",
      "PPT export — 15-slide & 5-slide decks",
      "In-browser presentation mode",
      "Share workspace links",
      "Paper comparison mode",
      "GPT-4o — full model",
      "RAG — smart semantic search across your paper",
      "Forever history",
    ],
    highlight: false,
    tagline: "Unlimited. Smarter. Built for serious academics",
  },
];
